extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 200
    level: warning

  # don't bother me with this rule
  indentation: disable
  empty-lines: 
    max: 20

  trailing-spaces: disable
  
  new-line-at-end-of-file: disable